// backend/cropSuggestions.js
module.exports = {
  wheat: {
    duration: 120,
    suggestions: [
      { days: [1], task: "Day 1: Plough the field deeply using a tractor to prepare the land." },
      { days: [2], task: "Day 2: Apply FYM (Farm Yard Manure) evenly across the field." },
      { days: [3], task: "Day 3: Level the field using a harrow and remove clods." },
      { days: [4], task: "Day 4: Sow wheat seeds with seed drill. Maintain spacing of 20 cm." },
      { days: [5], task: "Day 5: Water the field lightly to ensure seed germination." },
      { days: [6], task: "Day 6: Take rest and observe soil moisture level." },
      { days: [7], task: "Day 7: Check for seedling emergence and early pest attack." },
      { days: [8], task: "Day 8: Spray organic pest repellent if needed." },
      { days: [9], task: "Day 9: Take rest and monitor plant growth." },
      { days: [10], task: "Day 10: Apply light dose of urea fertilizer." },
      { days: [11], task: "Day 11: Water the field again if soil appears dry." },
      { days: [12], task: "Day 12: Inspect for weeds; hand remove small ones." },
      { days: [13], task: "Day 13: Continue weeding and leveling small water patches." },
      { days: [14], task: "Day 14: Spray fungicide if early disease symptoms appear." },
      { days: [15], task: "Day 15: Irrigate during evening hours for better absorption." },
      { days: [16], task: "Day 16: Take rest and inspect leaf color for nutrient health." },
      { days: [17], task: "Day 17: Apply potash if yellowing is seen in leaves." },
      { days: [18], task: "Day 18: Spray micronutrients if growth is slow." },
      { days: [19], task: "Day 19: Check for termite or insect attacks near roots." },
      { days: [20], task: "Day 20: Take rest and prepare for second weeding phase." },
      { days: [21], task: "Day 21: Do second weeding using conoweeder or manually." },
      { days: [22], task: "Day 22: Apply top-dress urea near the base of plants." },
      { days: [23], task: "Day 23: Water the field fully, avoid water stagnation." },
      { days: [24], task: "Day 24: Monitor plant tillering and remove weak shoots." },
      { days: [25], task: "Day 25: Take rest and observe for leaf rust or mildew." },
      { days: [26], task: "Day 26: Spray appropriate fungicide for leaf rust." },
      { days: [27], task: "Day 27: Apply DAP if needed (based on leaf analysis)." },
      { days: [28], task: "Day 28: Irrigate lightly. Avoid overwatering." },
      { days: [29], task: "Day 29: Rest. Monitor panicle initiation signs." },
      { days: [30], task: "Day 30: Crop enters flowering stage. Protect from birds." },
      { days: [31], task: "Day 31: Light water spray if temperature rises." },
      { days: [32], task: "Day 32: Take rest and clean the bunds around field." },
      { days: [33], task: "Day 33: Apply foliar spray for healthy flowering." },
      { days: [34], task: "Day 34: Check for aphid or pest attack at flowering stage." },
      { days: [35], task: "Day 35: Continue bird scaring and install noise makers." },
      { days: [36], task: "Day 36: Light irrigation during early morning." },
      { days: [37], task: "Day 37: Take rest and review growth stage." },
      { days: [38], task: "Day 38: Remove water stagnation if any due to rain." },
      { days: [39], task: "Day 39: Spray potassium nitrate to boost grain filling." },
      { days: [40], task: "Day 40: Apply urea if leaves are pale green." },
      { days: [41], task: "Day 41: Irrigate one last time during late evening." },
      { days: [42], task: "Day 42: Rest and monitor grain filling." },
      { days: [43], task: "Day 43: Start drying preparation like drainage cleaning." },
      { days: [44], task: "Day 44: Check grain hardness. Wait till 90% maturity." },
      { days: [45], task: "Day 45: Arrange labour or machine for harvesting." },
      { days: [46], task: "Day 46: Begin harvesting in early morning to avoid grain loss." },
      { days: [47], task: "Day 47: Dry harvested grains on clean surface under sun." },
      { days: [48], task: "Day 48: Turn grains regularly for uniform drying." },
      { days: [49], task: "Day 49: Clean and store wheat in dry, airtight bags." },
      { days: [50], task: "Day 50: Sell to nearby mandi or contact trader for better price." },
      { days: [51], task: "Day 51: Maintain field hygiene. Remove crop residues." },
      { days: [52], task: "Day 52: Rest and review entire crop process for improvement." },
      { days: [53], task: "Day 53: Store farming tools and maintain machinery." },
      { days: [54], task: "Day 54: Take rest. Celebrate successful harvest." },
      { days: [55], task: "Day 55: Begin land prep for next seasonal crop." },
      { days: [56], task: "Day 56: Keep harvested grain safe from pests." },
      { days: [57], task: "Day 57: Maintain contact with buyers and co-ops." },
      { days: [58], task: "Day 58: Analyze market rates for wheat." },
      { days: [59], task: "Day 59: Arrange transport for delivery." },
      { days: [60], task: "Day 60: Deliver stock to market or buyer." },
      { days: [61], task: "Day 61: Collect payment and record transaction." },
      { days: [62], task: "Day 62: Clean field area for next crop or rest season." },
      { days: [63], task: "Day 63: Rest and plan crop rotation." },
      { days: [64], task: "Day 64: Maintain accounts and cost analysis." },
      { days: [65], task: "Day 65: Inspect field boundaries for fencing or repairs." },
      { days: [66], task: "Day 66: Repair any damaged irrigation lines." },
      { days: [67], task: "Day 67: Prepare compost if needed for next season." },
      { days: [68], task: "Day 68: Monitor stored grain for any spoilage or pests." },
      { days: [69], task: "Day 69: Take rest." },
      { days: [70], task: "Day 70: Record lessons learned this season in a farm diary." },
      { days: [71], task: "Day 71: Begin checking seed options for next crop." },
      { days: [72], task: "Day 72: Rest or support other farmers in the village." },
      { days: [73], task: "Day 73: Inspect tractor, sprayer and tools." },
      { days: [74], task: "Day 74: Take rest." },
      { days: [75], task: "Day 75: Final storage check for wheat grain." },
      { days: [76], task: "Day 76: Start looking into weather patterns for next cycle." },
      { days: [77], task: "Day 77: Reassess financials and credit if needed." },
      { days: [78], task: "Day 78: Rest." },
      { days: [79], task: "Day 79: Fertilizer stock check for upcoming cycle." },
      { days: [80], task: "Day 80: Clean irrigation system thoroughly." },
      { days: [81], task: "Day 81: Rest." },
      { days: [82], task: "Day 82: Visit market to get updates on seed prices." },
      { days: [83], task: "Day 83: Start pre-ordering seeds if needed." },
      { days: [84], task: "Day 84: Take rest." },
      { days: [85], task: "Day 85: Analyze soil moisture and texture post-harvest." },
      { days: [86], task: "Day 86: Prepare organic compost from residue." },
      { days: [87], task: "Day 87: Rest and recharge." },
      { days: [88], task: "Day 88: Network with local co-op or farmer groups." },
      { days: [89], task: "Day 89: Review weather forecast and advisory." },
      { days: [90], task: "Day 90: Begin early land preparation for next cycle." },
      { days: [91], task: "Day 91: Final cleanup of field." },
      { days: [92], task: "Day 92: Take rest." },
      { days: [93], task: "Day 93: Inventory and repair tools." },
      { days: [94], task: "Day 94: Record expenses and income." },
      { days: [95], task: "Day 95: Plan future crop with agricultural officer." },
      { days: [96], task: "Day 96: Rest and monitor environment changes." },
      { days: [97], task: "Day 97: Final discussions with buyers about pricing." },
      { days: [98], task: "Day 98: Confirm future crop sowing schedule." },
      { days: [99], task: "Day 99: Rest." },
      { days: [100], task: "Day 100: Full cycle review and celebration." },
      { days: [101], task: "Day 101–120: Continue rest, field prep or transition to next crop." }
    ],
  },


   paddy: {
  duration: 120,
  suggestions: [
    { days: [1], task: "Day 1: Select field with adequate water supply." },
    { days: [2], task: "Day 2: Begin first ploughing and remove weeds." },
    { days: [3], task: "Day 3: Add 5–7 tons/acre of FYM or compost." },
    { days: [4], task: "Day 4: Level the land and prepare puddling for nursery." },
    { days: [5], task: "Day 5: Soak paddy seeds in water for 24 hours." },
    { days: [6], task: "Day 6: Keep seeds in gunny bags for sprouting." },
    { days: [7], task: "Day 7: Prepare nursery bed and sow sprouted seeds." },
    { days: [8], task: "Day 8: Provide light irrigation in nursery." },
    { days: [9], task: "Day 9: Monitor for damping-off, apply Trichoderma if needed." },
    { days: [10], task: "Day 10: Apply first dose of DAP in nursery (4–5 kg/cent)." },
    { days: [11], task: "Day 11: Observe seedling emergence and check for uniform growth." },
    { days: [12], task: "Day 12: Remove weeds manually in nursery." },
    { days: [13], task: "Day 13: Apply light irrigation, avoid standing water." },
    { days: [14], task: "Day 14: Spray neem oil if insect activity is observed." },
    { days: [15], task: "Day 15: Prepare main field with puddling and leveling." },
    { days: [16], task: "Day 16: Apply basal fertilizers – 50% N, full P and K." },
    { days: [17], task: "Day 17: Transplant 20–25 day old seedlings to main field." },
    { days: [18], task: "Day 18: Maintain 2–3 cm water in field." },
    { days: [19], task: "Day 19: Gap filling and remove weak seedlings." },
    { days: [20], task: "Day 20: Apply Azospirillum and Phosphobacteria as biofertilizers." },
    { days: [21], task: "Day 21: First top dressing with 25% of Nitrogen (Urea)." },
    { days: [22], task: "Day 22: Hand weeding or apply pre-emergent herbicide." },
    { days: [23], task: "Day 23: Light irrigation, maintain standing water." },
    { days: [24], task: "Day 24: Observe for leaf folder or stem borer attack." },
    { days: [25], task: "Day 25: Spray insecticide if pest population exceeds threshold." },
    { days: [26], task: "Day 26: Light hoeing near plant base for aeration." },
    { days: [27], task: "Day 27: Maintain proper plant spacing with rope dragging." },
    { days: [28], task: "Day 28: Monitor tillering stage (more shoots per plant)." },
    { days: [29], task: "Day 29: Apply 2nd top dressing – 25% Nitrogen (Urea)." },
    { days: [30], task: "Day 30: Check for yellowing due to iron deficiency." },
    { days: [31], task: "Day 31: Apply ferrous sulfate spray if deficiency seen." },
    { days: [32], task: "Day 32: Maintain 5 cm standing water consistently." },
    { days: [33], task: "Day 33: Watch for sheath blight or bacterial leaf blight." },
    { days: [34], task: "Day 34: Apply fungicide if sheath blight appears." },
    { days: [35], task: "Day 35: Ensure uniform growth and weed-free conditions." },
    { days: [36], task: "Day 36: Spray micronutrient mix if needed." },
    { days: [37], task: "Day 37: Check for panicle initiation stage." },
    { days: [38], task: "Day 38: Apply 3rd top dressing – 25% Nitrogen (Urea)." },
    { days: [39], task: "Day 39: Maintain standing water during panicle initiation." },
    { days: [40], task: "Day 40: Monitor booting stage (panicle swelling in leaf sheath)." },
    { days: [41], task: "Day 41: Apply Potash if not given in basal stage." },
    { days: [42], task: "Day 42: Observe flowering initiation in panicles." },
    { days: [43], task: "Day 43: Keep water level constant (4–5 cm)." },
    { days: [44], task: "Day 44: Avoid insecticide spraying during peak flowering." },
    { days: [45], task: "Day 45: Maintain field hygiene and clean bunds." },
    { days: [46], task: "Day 46: Foliar spray of Zinc sulfate if white leaf seen." },
    { days: [47], task: "Day 47: Monitor grain filling progress." },
    { days: [48], task: "Day 48: Apply final dose of nitrogen if needed (optional)." },
    { days: [49], task: "Day 49: Reduce water level gradually." },
    { days: [50], task: "Day 50: Observe signs of grain hardening." },
    { days: [51], task: "Day 51: Control rodents and birds with traps or guards." },
    { days: [52], task: "Day 52: Drain water completely before harvest (7–10 days before)." },
    { days: [53], task: "Day 53: Begin harvesting matured panicles from dry areas." },
    { days: [54], task: "Day 54: Complete harvest and transport to threshing floor." },
    { days: [55], task: "Day 55: Thresh harvested crop using manual or mechanical method." },
    { days: [56], task: "Day 56: Dry paddy in sun for 2–3 days." },
    { days: [57], task: "Day 57: Clean and winnow grains." },
    { days: [58], task: "Day 58: Store dried grains in gunny bags or bins." },
    { days: [59], task: "Day 59: Stack bags on wooden pallets to avoid moisture." },
    { days: [60], task: "Day 60: Weigh and record total yield from the season." },
    { days: [61], task: "Day 61: Sell paddy at market or to FCI/mandi." },
    { days: [62], task: "Day 62: Begin field cleaning and residue management." },
    { days: [63], task: "Day 63: Compost paddy straw if not used as fodder." },
    { days: [64], task: "Day 64: Start drying and storing own seeds if needed." },
    { days: [65], task: "Day 65: Label and store seeds in dry airtight containers." },
    { days: [66], task: "Day 66: Clean and maintain farm tools." },
    { days: [67], task: "Day 67: Review season’s performance and costs." },
    { days: [68], task: "Day 68: Attend farmer meetings or training." },
    { days: [69], task: "Day 69: Plan intercrop if field is free early." },
    { days: [70], task: "Day 70: Record fertilizer and pesticide usage data." },
    { days: [71], task: "Day 71: Apply gypsum/lime if soil requires." },
    { days: [72], task: "Day 72: Check stored grain for pest/mold regularly." },
    { days: [73], task: "Day 73: Turn grain bags periodically to avoid heating." },
    { days: [74], task: "Day 74: Clean storage room and remove spills." },
    { days: [75], task: "Day 75: Inspect irrigation equipment for damage." },
    { days: [76], task: "Day 76: Replace broken sickles or buckets." },
    { days: [77], task: "Day 77: Begin rough planning for next season’s inputs." },
    { days: [78], task: "Day 78: Interact with agri-dealers for seeds/fertilizer." },
    { days: [79], task: "Day 79: Visit Krishi Vigyan Kendra for new updates." },
    { days: [80], task: "Day 80: Conduct soil testing again if not done before." },
    { days: [81], task: "Day 81: Begin budgeting for next crop cycle." },
    { days: [82], task: "Day 82: Record market price trends for next plan." },
    { days: [83], task: "Day 83: Service threshers, winnowers and sprayers." },
    { days: [84], task: "Day 84: Arrange storage space for upcoming season." },
    { days: [85], task: "Day 85: Rest and reflect on season’s learning." },
    { days: [86], task: "Day 86: Reorganize nursery trays or sowing containers." },
    { days: [87], task: "Day 87: Turn compost pile to accelerate breakdown." },
    { days: [88], task: "Day 88: Create checklist of agri-operations done." },
    { days: [89], task: "Day 89: Begin minor repairs in bunds/channels." },
    { days: [90], task: "Day 90: Collect feedback from buyers or co-ops." },
    { days: [91], task: "Day 91: Begin raising seedlings if sowing again soon." },
    { days: [92], task: "Day 92: Monitor stored seeds and grains." },
    { days: [93], task: "Day 93: Clean plastic sheets and drying platforms." },
    { days: [94], task: "Day 94: Spray repellents in store room if rodents seen." },
    { days: [95], task: "Day 95: Sharpen and oil tools to avoid rusting." },
    { days: [96], task: "Day 96: Prepare sowing calendar for next season." },
    { days: [97], task: "Day 97: Visit other farms to exchange knowledge." },
    { days: [98], task: "Day 98: Check agri schemes for support or subsidy." },
    { days: [99], task: "Day 99: Wash and sun-dry cloth bags or sacks." },
    { days: [100], task: "Day 100: Conduct inventory of leftover inputs." },
    { days: [101], task: "Day 101: Start land prep if double crop planned." },
    { days: [102], task: "Day 102: List vendors for required materials." },
    { days: [103], task: "Day 103: Attend market to study demand trend." },
    { days: [104], task: "Day 104: Final cleanup of nursery site." },
    { days: [105], task: "Day 105: Visit agri-office if certificate or support needed." },
    { days: [106], task: "Day 106: Talk with agri-input providers for early booking." },
    { days: [107], task: "Day 107: Set up pest traps in storage if needed." },
    { days: [108], task: "Day 108: Apply cow dung slurry near bunds for sealing." },
    { days: [109], task: "Day 109: Final accounting and yield summary." },
    { days: [110], task: "Day 110: Rest and prepare mentally for new crop cycle." },
    { days: [111], task: "Day 111: Final field check before sowing again." },
    { days: [112], task: "Day 112: Send soil and grain samples if required." },
    { days: [113], task: "Day 113: Create document folder for current season." },
    { days: [114], task: "Day 114: Store empty fertilizer/pesticide bags safely." },
    { days: [115], task: "Day 115: Attend online agriculture training if interested." },
    { days: [116], task: "Day 116: Disinfect storage rooms if needed." },
    { days: [117], task: "Day 117: Organize team meeting with laborers." },
    { days: [118], task: "Day 118: Revisit yield goals and planning charts." },
    { days: [119], task: "Day 119: Ready land for nursery of next crop." },
    { days: [120], task: "Day 120: Start new season with experience from this one!" }
  ]
},

    tomato: {
    duration: 110,
    suggestions: [
      { days: [1], task: "Day 1: Select site and start ploughing field with tractor." },
      { days: [2], task: "Day 2: Apply well-decomposed FYM and level field." },
      { days: [3], task: "Day 3: Prepare raised nursery beds with fine tilth." },
      { days: [4], task: "Day 4: Sow tomato seeds in nursery with proper spacing." },
      { days: [5], task: "Day 5: Cover beds lightly with straw and irrigate gently." },
      { days: [6], task: "Day 6: Observe for seed germination signs." },
      { days: [7], task: "Day 7: Remove straw cover and expose seedlings to sunlight." },
      { days: [8], task: "Day 8: Spray fungicide if signs of damping-off appear." },
      { days: [9], task: "Day 9: Light irrigation of nursery bed in early morning." },
      { days: [10], task: "Day 10: Begin hardening by reducing water slowly." },
      { days: [11], task: "Day 11: Continue nursery care. Remove weeds by hand." },
      { days: [12], task: "Day 12: Prepare main field by adding basal dose fertilizers." },
      { days: [13], task: "Day 13: Make ridges and furrows with 60cm spacing." },
      { days: [14], task: "Day 14: Transplant 25-day old seedlings to main field." },
      { days: [15], task: "Day 15: Irrigate field gently to help seedlings settle." },
      { days: [16], task: "Day 16: Provide shade using coconut leaves if too sunny." },
      { days: [17], task: "Day 17: Observe for any wilt or transplant shock." },
      { days: [18], task: "Day 18: Apply first dose of nitrogen fertilizer." },
      { days: [19], task: "Day 19: Install stakes for support as plants grow." },
      { days: [20], task: "Day 20: Light irrigation and inspect for pest attacks." },
      { days: [21], task: "Day 21: Spray neem oil for sucking pests like aphids." },
      { days: [22], task: "Day 22: Start weeding between ridges." },
      { days: [23], task: "Day 23: Apply potash to improve root strength." },
      { days: [24], task: "Day 24: Check leaves for early blight or curling." },
      { days: [25], task: "Day 25: Spray fungicide if disease appears." },
      { days: [26], task: "Day 26: Tie plants gently to stakes with thread." },
      { days: [27], task: "Day 27: Second round of irrigation." },
      { days: [28], task: "Day 28: Remove lower yellowing leaves." },
      { days: [29], task: "Day 29: Apply foliar spray of micronutrients." },
      { days: [30], task: "Day 30: Check flower buds starting to appear." },
      { days: [31], task: "Day 31: Light irrigation during flowering stage." },
      { days: [32], task: "Day 32: Spray boron to improve flower retention." },
      { days: [33], task: "Day 33: Remove weeds manually." },
      { days: [34], task: "Day 34: Observe fruit set from lower branches." },
      { days: [35], task: "Day 35: Spray potassium nitrate to support fruit growth." },
      { days: [36], task: "Day 36: Light irrigation without wetting fruits." },
      { days: [37], task: "Day 37: Check for fruit borer or mites." },
      { days: [38], task: "Day 38: Use pheromone traps or spray botanical insecticide." },
      { days: [39], task: "Day 39: Provide additional staking support as needed." },
      { days: [40], task: "Day 40: Remove old/diseased leaves to improve airflow." },
      { days: [41], task: "Day 41: Water plants during early morning only." },
      { days: [42], task: "Day 42: Apply final top-dress fertilizer with potash." },
      { days: [43], task: "Day 43: Continue fruit harvest from lower clusters." },
      { days: [44], task: "Day 44: Spray calcium nitrate if blossom-end rot is seen." },
      { days: [45], task: "Day 45: Continue regular harvesting of ripe tomatoes." },
      { days: [46], task: "Day 46: Clean baskets and sort tomatoes for market." },
      { days: [47], task: "Day 47: Transport tomatoes to local market." },
      { days: [48], task: "Day 48: Irrigate and remove rotten fruits from plants." },
      { days: [49], task: "Day 49: Maintain clean surroundings to reduce pests." },
      { days: [50], task: "Day 50: Harvest second flush of ripened fruits." },
      { days: [51], task: "Day 51: Continue marketing or sell to wholesaler." },
      { days: [52], task: "Day 52: Monitor for late blight in rainy season." },
      { days: [53], task: "Day 53: Spray suitable fungicide for late diseases." },
      { days: [54], task: "Day 54: Begin crop residue removal from harvested plants." },
      { days: [55], task: "Day 55: Final harvesting of remaining fruits." },
      { days: [56], task: "Day 56: Clear field completely and remove support sticks." },
      { days: [57], task: "Day 57: Begin composting leftover organic matter." },
      { days: [58], task: "Day 58: Dry and store leftover tomatoes for seed saving if needed." },
      { days: [59], task: "Day 59: Record harvest quantities and income." },
      { days: [60], task: "Day 60: Store tools and rest." },
      { days: [61], task: "Day 61: Reflect on crop performance and plan improvements." },
      { days: [62], task: "Day 62: Begin planning for next tomato or other crop cycle." },
      { days: [63], task: "Day 63: Inspect plants for regrowth and remove any diseased parts." },
      { days: [64], task: "Day 64: Start basic maintenance if growing indeterminate varieties." },
      { days: [65], task: "Day 65: Harvest any late bloom fruits if present." },
      { days: [66], task: "Day 66: Monitor plant decay and prepare for final clearance." },
      { days: [67], task: "Day 67: Final field cleanup and composting." },
      { days: [68], task: "Day 68: Begin checking market trends for next cycle." },
      { days: [69], task: "Day 69: Record expenses and prepare budget for next crop." },
      { days: [70], task: "Day 70: Take rest or support other farmers in the village." },
      { days: [71], task: "Day 71: Maintain tomato storage condition." },
      { days: [72], task: "Day 72: Sell dried/saved seeds to other farmers if possible." },
      { days: [73], task: "Day 73: Repair and maintain farm tools and equipment." },
      { days: [74], task: "Day 74: Begin light tilling for next seasonal crop." },
      { days: [75], task: "Day 75: Monitor weather forecasts for coming season." },
      { days: [76], task: "Day 76: Evaluate soil health and nutrient status." },
      { days: [77], task: "Day 77: Order seeds and fertilizers in advance." },
      { days: [78], task: "Day 78: Take rest." },
      { days: [79], task: "Day 79: Clean irrigation channels and store pipes properly." },
      { days: [80], task: "Day 80: Document lessons learned and update farm diary." },
      { days: [81], task: "Day 81: Take rest or attend any farming training nearby." },
      { days: [82], task: "Day 82: Re-check storage for pests or moisture." },
      { days: [83], task: "Day 83: Support community work or educate young farmers." },
      { days: [84], task: "Day 84: Maintain fencing and check water sources." },
      { days: [85], task: "Day 85: Review previous cycle's profits and prepare future goals." },
      { days: [86], task: "Day 86: Continue soil preparation for next season." },
      { days: [87], task: "Day 87: Rest and relax." },
      { days: [88], task: "Day 88: Begin preparing nursery trays for next crop if required." },
      { days: [89], task: "Day 89: Participate in local farmer meetups if available." },
      { days: [90], task: "Day 90: Continue light land prep for next round." },
      { days: [91], task: "Day 91: Organize harvest data and photos if needed for subsidy." },
      { days: [92], task: "Day 92: Rest and visit agriculture extension office if required." },
      { days: [93], task: "Day 93: Final planning for upcoming crop." },
      { days: [94], task: "Day 94: Contact labor or workers for field work." },
      { days: [95], task: "Day 95: Pre-book tractor or harrow service." },
      { days: [96], task: "Day 96: Maintain clear storage and compost units." },
      { days: [97], task: "Day 97: Clean and disinfect seed storage area." },
      { days: [98], task: "Day 98: Test water source if possible." },
      { days: [99], task: "Day 99: Take full rest or refresh training." },
      { days: [100], task: "Day 100: Finalize seed list and crop rotation plans." },
      { days: [101], task: "Day 101–110: Light work, rest, and readiness for new crop cycle." }
    ]
  },
  cotton: {
    duration: 160,
    suggestions: [
      { days: [1], task: "Day 1: Begin deep ploughing of the field to destroy previous crop residues." },
      { days: [2], task: "Day 2: Apply FYM and compost, then leave for decomposition." },
      { days: [3], task: "Day 3: Level the field and create ridges and furrows." },
      { days: [4], task: "Day 4: Apply basal fertilizers rich in phosphorus and potash." },
      { days: [5], task: "Day 5: Treat seeds with fungicide or Trichoderma for disease prevention." },
      { days: [6], task: "Day 6: Sow cotton seeds with 60–90 cm spacing using seed drill/manual sowing." },
      { days: [7], task: "Day 7: Provide light irrigation if soil is dry." },
      { days: [8], task: "Day 8: Monitor germination and protect young seedlings from ants or birds." },
      { days: [9], task: "Day 9: Start thinning extra seedlings if multiple germinate per spot." },
      { days: [10], task: "Day 10: Observe for any early pest attack (aphids, jassids)." },
      { days: [11], task: "Day 11: Spray neem oil or recommended insecticide if needed." },
      { days: [12], task: "Day 12: Light hoeing to break crust and improve aeration." },
      { days: [13], task: "Day 13: Irrigate if no rain in past 3 days." },
      { days: [14], task: "Day 14: Apply top-dress nitrogen to boost vegetative growth." },
      { days: [15], task: "Day 15: Monitor for wilting, leaf curling symptoms." },
      { days: [16], task: "Day 16: Spray fungicide if fungal disease observed." },
      { days: [17], task: "Day 17: Begin weeding using hand hoe or intercultivator." },
      { days: [18], task: "Day 18: Apply micronutrients like magnesium and zinc." },
      { days: [19], task: "Day 19: Observe plant height and spacing, do gap filling if needed." },
      { days: [20], task: "Day 20: Rest and observe field condition." },
      { days: [21], task: "Day 21: Continue irrigation every 7–10 days if dry." },
      { days: [22], task: "Day 22: Install yellow sticky traps to monitor sucking pests." },
      { days: [23], task: "Day 23: Check for red cotton bug or mealy bug." },
      { days: [24], task: "Day 24: Spray botanical insecticide if needed." },
      { days: [25], task: "Day 25: Begin earthing-up (heaping soil around roots)." },
      { days: [26], task: "Day 26: Ensure no waterlogging occurs." },
      { days: [27], task: "Day 27: Start squaring (bud formation) stage." },
      { days: [28], task: "Day 28: Apply second dose of nitrogen and potash." },
      { days: [29], task: "Day 29: Light irrigation if needed." },
      { days: [30], task: "Day 30: Monitor for spotted bollworm and helicoverpa." },
      { days: [31], task: "Day 31: Set pheromone traps to reduce bollworm." },
      { days: [32], task: "Day 32: Continue regular field visit and plant inspection." },
      { days: [33], task: "Day 33: Spray fungicide if leaf spot symptoms appear." },
      { days: [34], task: "Day 34: Rest and inspect weather forecasts." },
      { days: [35], task: "Day 35: Flowering begins. Avoid chemical spray during bloom." },
      { days: [36], task: "Day 36: Light irrigation to maintain moisture for flower setting." },
      { days: [37], task: "Day 37: Observe flower drop and consult agri expert if heavy drop." },
      { days: [38], task: "Day 38: Support weak plants with bamboo or stick." },
      { days: [39], task: "Day 39: Check for pink bollworm infestation." },
      { days: [40], task: "Day 40: Spray recommended pesticide only if threshold crossed." },
      { days: [41], task: "Day 41: Remove pest-affected squares/bolls manually." },
      { days: [42], task: "Day 42: Foliar spray of NPK for boll development." },
      { days: [43], task: "Day 43: Continue weed control manually." },
      { days: [44], task: "Day 44: Monitor boll size and firmness." },
      { days: [45], task: "Day 45: Second top-dress fertilizer dose." },
      { days: [46], task: "Day 46: Irrigate gently, avoid wetting bolls." },
      { days: [47], task: "Day 47: Rest and observe plant health." },
      { days: [48], task: "Day 48: Start noticing boll opening on early plants." },
      { days: [49], task: "Day 49: Remove dried and dead leaves from bottom of plant." },
      { days: [50], task: "Day 50: Start picking open cotton bolls manually." },
      { days: [51], task: "Day 51: Continue second round of picking." },
      { days: [52], task: "Day 52: Dry harvested cotton in shade." },
      { days: [53], task: "Day 53: Store cotton in ventilated room, avoid moisture." },
      { days: [54], task: "Day 54: Begin cleaning cotton before marketing." },
      { days: [55], task: "Day 55: Continue third round of picking if needed." },
      { days: [56], task: "Day 56: Transport first batch to local market/ginning mill." },
      { days: [57], task: "Day 57: Continue drying and storing further picks." },
      { days: [58], task: "Day 58: Clean field of dropped cotton and weed growth." },
      { days: [59], task: "Day 59: Continue pest scouting on late-stage bolls." },
      { days: [60], task: "Day 60: Prepare documents and receipts for sold produce." },
        { days: [62], task: "Day 62: Inspect boll weight and quality for pricing." },
  { days: [63], task: "Day 63: Sort cotton grades and pack properly for transport." },
  { days: [64], task: "Day 64: Remove any spoiled cotton or sacks." },
  { days: [65], task: "Day 65: Start clearing field and preparing compost pile." },
  { days: [66], task: "Day 66: Take rest and plan remaining harvest." },
  { days: [67], task: "Day 67: Final round of picking and field cleanup." },
  { days: [68], task: "Day 68: Store all tools, wrap up cotton drying areas." },
  { days: [69], task: "Day 69: Final weigh-in and cotton bundling." },
  { days: [70], task: "Day 70: Sell remaining produce to co-op or buyer." },
  { days: [71], task: "Day 71: Clean storage area and return rental tools." },
  { days: [72], task: "Day 72: Monitor soil and check pest status post-harvest." },
  { days: [73], task: "Day 73: Conduct soil testing for nutrient management." },
  { days: [74], task: "Day 74: Apply lime or gypsum based on test result." },
  { days: [75], task: "Day 75: Compost application and incorporate residues." },
  { days: [76], task: "Day 76: Begin land preparation for next crop." },
  { days: [77], task: "Day 77: Take rest and evaluate crop performance." },
  { days: [78], task: "Day 78: Record expenses, profit, and yield for season." },
  { days: [79], task: "Day 79: Attend agri-training or visit extension office." },
  { days: [80], task: "Day 80: Repair irrigation lines and farm fencing." },
  { days: [81], task: "Day 81: Rotate grazing or let field rest if fallow." },
  { days: [82], task: "Day 82: Clean storage sacks and cotton drying mats." },
  { days: [83], task: "Day 83: Prepare budget for next sowing season." },
  { days: [84], task: "Day 84: Organize laborers for upcoming works." },
  { days: [85], task: "Day 85: Sharpen tools and service farm equipment." },
  { days: [86], task: "Day 86: Check market trends for future cotton price." },
  { days: [87], task: "Day 87: Re-check stored cotton for pests and mold." },
  { days: [88], task: "Day 88: Sell or donate old/unused tools." },
  { days: [89], task: "Day 89: Rest or volunteer with neighbor farms." },
  { days: [90], task: "Day 90: Replant cover crops or legumes to improve soil." },
  { days: [91], task: "Day 91: Record all learnings in farmer diary." },
  { days: [92], task: "Day 92: Rest and spend time with family." },
  { days: [93], task: "Day 93: Inventory seed stock for next crop." },
  { days: [94], task: "Day 94: Purchase new seeds or inputs if needed." },
  { days: [95], task: "Day 95: Clean compost pits and recycle materials." },
  { days: [96], task: "Day 96: Dry, clean, and organize harvest records." },
  { days: [97], task: "Day 97: Confirm field is ready for next sowing." },
  { days: [98], task: "Day 98: Visit local market to analyze pricing pattern." },
  { days: [99], task: "Day 99: Share knowledge with nearby farmers or groups." },
  { days: [100], task: "Day 100: Take full rest." },
  { days: [101], task: "Day 101: Maintain equipment and continue planning." },
  { days: [102], task: "Day 102: Monitor weeds or pests before new crop cycle." },
  { days: [103], task: "Day 103: Inspect compost quality for next use." },
  { days: [104], task: "Day 104: Engage in farmer meetings if available." },
  { days: [105], task: "Day 105: Confirm input supply and logistics." },
  { days: [106], task: "Day 106: Check tractor availability and labor schedule." },
  { days: [107], task: "Day 107: Final round of tool repairs and sharpening." },
  { days: [108], task: "Day 108: Clean and prep seed bins and nursery trays." },
  { days: [109], task: "Day 109: Analyze past crop data and refine plan." },
  { days: [110], task: "Day 110: Begin next round of pre-sowing operations." }
   ],
  },


    chilli: {
    duration: 120,
    suggestions: [
     { days: [1], task: "Day 1: Select site, begin ploughing and clearing the land." },
  { days: [2], task: "Day 2: Add FYM/compost and level the soil." },
  { days: [3], task: "Day 3: Prepare nursery beds with good drainage." },
  { days: [4], task: "Day 4: Sow chilli seeds in nursery beds." },
  { days: [5], task: "Day 5: Cover lightly with straw and water gently." },
  { days: [6], task: "Day 6: Observe germination and protect from birds." },
  { days: [7], task: "Day 7: Provide shade and light irrigation." },
  { days: [8], task: "Day 8: Spray fungicide to prevent damping-off." },
  { days: [9], task: "Day 9: Weeding and checking for pests in nursery." },
  { days: [10], task: "Day 10: Prepare main field with ridges and furrows." },
  { days: [11], task: "Day 11: Apply basal fertilizers (phosphorus, potash)." },
  { days: [12], task: "Day 12: Harden nursery seedlings by reducing water." },
  { days: [13], task: "Day 13: Final irrigation of nursery before transplanting." },
  { days: [14], task: "Day 14: Transplant 30-35 day old seedlings to field." },
  { days: [15], task: "Day 15: Water gently and provide partial shade." },
  { days: [16], task: "Day 16: Monitor transplant success and replant gaps." },
  { days: [17], task: "Day 17: Light hoeing to prevent crusting of soil." },
  { days: [18], task: "Day 18: Observe for leaf curl or wilting signs." },
  { days: [19], task: "Day 19: Apply nitrogenous fertilizer for vegetative growth." },
  { days: [20], task: "Day 20: Irrigate and maintain uniform moisture." },
  { days: [21], task: "Day 21: Start staking to support growing plants." },
  { days: [22], task: "Day 22: Apply neem oil for whitefly or thrips control." },
  { days: [23], task: "Day 23: Remove weeds manually from beds." },
  { days: [24], task: "Day 24: Spray micronutrients for healthy foliage." },
  { days: [25], task: "Day 25: Check for early flowering signs." },
  { days: [26], task: "Day 26: Irrigate lightly, avoid water stagnation." },
  { days: [27], task: "Day 27: Monitor for fruit borer larvae." },
  { days: [28], task: "Day 28: Install pheromone traps if pest activity noted." },
  { days: [29], task: "Day 29: Apply second top-dress of fertilizer." },
  { days: [30], task: "Day 30: Begin first harvest of green chillies." },
  { days: [31], task: "Day 31: Sort and grade harvested chillies." },
  { days: [32], task: "Day 32: Continue harvesting ripe green fruits." },
  { days: [33], task: "Day 33: Irrigate lightly to maintain flower production." },
  { days: [34], task: "Day 34: Spray potassium nitrate for better fruiting." },
  { days: [35], task: "Day 35: Remove yellow or infected leaves." },
  { days: [36], task: "Day 36: Second round of chilli picking." },
  { days: [37], task: "Day 37: Spray fungicide if leaf spot appears." },
  { days: [38], task: "Day 38: Sort and dry chillies in partial sun." },
  { days: [39], task: "Day 39: Monitor for anthracnose or powdery mildew." },
  { days: [40], task: "Day 40: Apply fungicide if disease confirmed." },
  { days: [41], task: "Day 41: Continue third round of chilli harvesting." },
  { days: [42], task: "Day 42: Grade and pack fruits for market." },
  { days: [43], task: "Day 43: Take chillies to local mandi or buyer." },
  { days: [44], task: "Day 44: Irrigate and check soil moisture." },
  { days: [45], task: "Day 45: Inspect remaining plants for fruit rot." },
  { days: [46], task: "Day 46: Fourth harvest and grading." },
  { days: [47], task: "Day 47: Dry chillies if storing or processing." },
  { days: [48], task: "Day 48: Remove any fallen or rotten fruits." },
  { days: [49], task: "Day 49: Observe flowering and new bud growth." },
  { days: [50], task: "Day 50: Apply final dose of potash fertilizer." },
  { days: [51], task: "Day 51: Fifth harvest round." },
  { days: [52], task: "Day 52: Clean field and mulch if possible." },
  { days: [53], task: "Day 53: Evaluate yield and grade performance." },
  { days: [54], task: "Day 54: Market the fifth round produce." },
  { days: [55], task: "Day 55: Monitor for late-stage diseases." },
  { days: [56], task: "Day 56: Rest and maintain post-harvest hygiene." },
  { days: [57], task: "Day 57: Sixth harvest and drying." },
  { days: [58], task: "Day 58: Fertilize if plants still flowering." },
  { days: [59], task: "Day 59: Grade and pack for local or distant sale." },
  { days: [60], task: "Day 60: Begin removing older dry plants." },
  { days: [61], task: "Day 61: Continue harvesting and cleanup." },
  { days: [62], task: "Day 62: Final harvest round." },
  { days: [63], task: "Day 63: Remove all debris and plant residues." },
  { days: [64], task: "Day 64: Sun-dry harvested chillies for storage." },
  { days: [65], task: "Day 65: Begin composting crop waste." },
  { days: [66], task: "Day 66: Sort dried chillies for seed collection." },
  { days: [67], task: "Day 67: Weigh and record final yield." },
  { days: [68], task: "Day 68: Rest and reflect on crop season." },
  { days: [69], task: "Day 69: Clean storage area and packaging tools." },
  { days: [70], task: "Day 70: Clean packing tools and empty crates." },
  { days: [71], task: "Day 71: Inspect dried chillies for mold or pests." },
  { days: [72], task: "Day 72: Prepare dried chillies for long-term storage." },
  { days: [73], task: "Day 73: Rotate stored bags to prevent moisture buildup." },
  { days: [74], task: "Day 74: Begin removing old stalks and composting them." },
  { days: [75], task: "Day 75: Conduct soil testing for next planting season." },
  { days: [76], task: "Day 76: Record yield, quality, and price received." },
  { days: [77], task: "Day 77: Attend a local farmer training workshop." },
  { days: [78], task: "Day 78: Service irrigation lines and repair leaks." },
  { days: [79], task: "Day 79: Apply gypsum or lime if soil requires correction." },
  { days: [80], task: "Day 80: Discuss market strategy with local buyers." },
  { days: [81], task: "Day 81: Join or attend farmer group meetings." },
  { days: [82], task: "Day 82: Rotate crops if planning intercrop next season." },
  { days: [83], task: "Day 83: Final cleaning of chillies for packaging." },
  { days: [84], task: "Day 84: Store seeds collected from best chillies." },
  { days: [85], task: "Day 85: Organize storage area and pest-proof it." },
  { days: [86], task: "Day 86: Rest and relax; evaluate seasonal expenses." },
  { days: [87], task: "Day 87: Replace damaged tools or buckets." },
  { days: [88], task: "Day 88: Compost turning and watering." },
  { days: [89], task: "Day 89: Visit nearby farm for learning exchange." },
  { days: [90], task: "Day 90: Begin land prep for short-term intercrop." },
  { days: [91], task: "Day 91: Apply compost to fallow areas." },
  { days: [92], task: "Day 92: Re-check stored chillies and rotate bags." },
  { days: [93], task: "Day 93: Evaluate season’s pest/disease control methods." },
  { days: [94], task: "Day 94: Reorganize water tanks or hoses." },
  { days: [95], task: "Day 95: Buy or order seeds for next season." },
  { days: [96], task: "Day 96: Create rough sowing calendar for next cycle." },
  { days: [97], task: "Day 97: Clean sprayers and protective gear." },
  { days: [98], task: "Day 98: List all inputs required and check availability." },
  { days: [99], task: "Day 99: Label and store saved seeds in airtight jars." },
  { days: [100], task: "Day 100: Rest or help nearby farmers if free." },
  { days: [101], task: "Day 101: Arrange labor for next sowing stage." },
  { days: [102], task: "Day 102: Weigh and sell remaining dried produce." },
  { days: [103], task: "Day 103: Begin field-leveling for next crop." },
  { days: [104], task: "Day 104: Apply basal manure to enrich field." },
  { days: [105], task: "Day 105: Review last season’s records and optimize." },
  { days: [106], task: "Day 106: Wash and repair nursery trays and containers." },
  { days: [107], task: "Day 107: Start soaking seeds for germination test." },
  { days: [108], task: "Day 108: Organize storage documents and sale receipts." },
  { days: [109], task: "Day 109: Broadcast cover crop seeds if applicable." },
  { days: [110], task: "Day 110: Final day of rest and planning before new cycle." }
    ],
    },



jowar: {
  duration: 110,
  suggestions: [
    { days: [1], task: "Day 1: Select land with good drainage and sunlight." },
    { days: [2], task: "Day 2: Start ploughing the land thoroughly." },
    { days: [3], task: "Day 3: Apply FYM/compost and incorporate into soil." },
    { days: [4], task: "Day 4: Level the field and break large clods." },
    { days: [5], task: "Day 5: Perform soil testing for nutrient availability." },
    { days: [6], task: "Day 6: Mark rows and spacing for sowing." },
    { days: [7], task: "Day 7: Sow Jowar seeds at appropriate spacing." },
    { days: [8], task: "Day 8: Provide light irrigation after sowing." },
    { days: [9], task: "Day 9: Monitor germination and protect from birds." },
    { days: [10], task: "Day 10: Apply pre-emergence herbicide if needed." },
    { days: [11], task: "Day 11: Check for uniform crop stand." },
    { days: [12], task: "Day 12: Re-sow in gaps to maintain population." },
    { days: [13], task: "Day 13: Light hoeing to control weeds." },
    { days: [14], task: "Day 14: First irrigation if soil moisture is low." },
    { days: [15], task: "Day 15: Monitor for shoot fly or aphid attack." },
    { days: [16], task: "Day 16: Apply insecticide if pest attack observed." },
    { days: [17], task: "Day 17: Conduct inter-row cultivation." },
    { days: [18], task: "Day 18: Apply nitrogen fertilizer as top dressing." },
    { days: [19], task: "Day 19: Second round of weeding if needed." },
    { days: [20], task: "Day 20: Irrigate if signs of moisture stress appear." },
    { days: [21], task: "Day 21: Check for stem borer infestation." },
    { days: [22], task: "Day 22: Apply neem extract or insecticide if required." },
    { days: [23], task: "Day 23: Observe tillering stage progress." },
    { days: [24], task: "Day 24: Perform earthing up near roots." },
    { days: [25], task: "Day 25: Irrigate to support vegetative growth." },
    { days: [26], task: "Day 26: Foliar spray of micronutrients." },
    { days: [27], task: "Day 27: Monitor for leaf blight or rust." },
    { days: [28], task: "Day 28: Apply fungicide if disease appears." },
    { days: [29], task: "Day 29: Inspect root zone moisture and weed status." },
    { days: [30], task: "Day 30: Second top dressing of nitrogen." },
    { days: [31], task: "Day 31: Observe panicle initiation stage." },
    { days: [32], task: "Day 32: Irrigate at panicle initiation if dry." },
    { days: [33], task: "Day 33: Apply potassium fertilizer to boost grain filling." },
    { days: [34], task: "Day 34: Monitor for shoot fly during panicle emergence." },
    { days: [35], task: "Day 35: Apply insecticide if pest threshold crossed." },
    { days: [36], task: "Day 36: Spray micronutrients to support flowering." },
    { days: [37], task: "Day 37: Inspect flowering progress and pollination." },
    { days: [38], task: "Day 38: Avoid water stress during flowering stage." },
    { days: [39], task: "Day 39: Continue monitoring for pest/disease." },
    { days: [40], task: "Day 40: Keep field clean and weed-free." },
    { days: [41], task: "Day 41: Begin grain filling observation." },
    { days: [42], task: "Day 42: Irrigate during grain development." },
    { days: [43], task: "Day 43: Apply final foliar nutrients if needed." },
    { days: [44], task: "Day 44: Observe for midge fly or earhead bugs." },
    { days: [45], task: "Day 45: Spray insecticide if grain damage seen." },
    { days: [46], task: "Day 46: Reduce irrigation frequency gradually." },
    { days: [47], task: "Day 47: Remove damaged or pest-affected ears." },
    { days: [48], task: "Day 48: Check for signs of maturity (grain hardening)." },
    { days: [49], task: "Day 49: Stop irrigation to allow drying." },
    { days: [50], task: "Day 50: First harvest trial of matured heads." },
    { days: [51], task: "Day 51: Harvest mature heads batch-wise." },
    { days: [52], task: "Day 52: Dry harvested ears in sun for 3–4 days." },
    { days: [53], task: "Day 53: Second batch of earhead harvest." },
    { days: [54], task: "Day 54: Thresh dried ears to extract grains." },
    { days: [55], task: "Day 55: Clean and winnow the grains." },
    { days: [56], task: "Day 56: Sun-dry grains to safe moisture level (12%)." },
    { days: [57], task: "Day 57: Begin bagging and storage of grains." },
    { days: [58], task: "Day 58: Store in clean, pest-proof containers." },
    { days: [59], task: "Day 59: Evaluate yield and calculate expenses." },
    { days: [60], task: "Day 60: Sell produce in local mandi or co-op." },
    { days: [61], task: "Day 61: Start clearing field residues and debris." },
    { days: [62], task: "Day 62: Compost crop residues or burn safely." },
    { days: [63], task: "Day 63: Conduct soil test for next season." },
    { days: [64], task: "Day 64: Clean and store tools used." },
    { days: [65], task: "Day 65: Attend training or visit Krishi Vigyan Kendra." },
    { days: [66], task: "Day 66: Begin documentation of seasonal records." },
    { days: [67], task: "Day 67: If seed is needed, identify best heads." },
    { days: [68], task: "Day 68: Dry and preserve seeds for next sowing." },
    { days: [69], task: "Day 69: Label and store seeds in airtight bags." },
    { days: [70], task: "Day 70: Monitor storage condition for pest/mold." },
    { days: [71], task: "Day 71: Plan crop rotation for next season." },
    { days: [72], task: "Day 72: Begin composting pit if not started." },
    { days: [73], task: "Day 73: Apply lime or gypsum if soil pH imbalance." },
    { days: [74], task: "Day 74: Service irrigation lines and equipment." },
    { days: [75], task: "Day 75: Clean storage shed and remove debris." },
    { days: [76], task: "Day 76: Record market price trends." },
    { days: [77], task: "Day 77: Interact with farmer groups or cooperatives." },
    { days: [78], task: "Day 78: Review pest control methods used." },
    { days: [79], task: "Day 79: Visit nearby demo farms if available." },
    { days: [80], task: "Day 80: Replace or repair broken tools." },
    { days: [81], task: "Day 81: Document weather patterns for season." },
    { days: [82], task: "Day 82: Plan budget for next cultivation." },
    { days: [83], task: "Day 83: Start early land prep for rabi season." },
    { days: [84], task: "Day 84: Select intercrop if planning mixed farming." },
    { days: [85], task: "Day 85: Arrange for next season’s inputs." },
    { days: [86], task: "Day 86: Attend local agri-market meeting." },
    { days: [87], task: "Day 87: Review rainfall data and drainage needs." },
    { days: [88], task: "Day 88: Dry remaining produce if not sold." },
    { days: [89], task: "Day 89: Prepare report for Kisan Credit or insurance." },
    { days: [90], task: "Day 90: Rest and recharge; reflect on improvements." },
    { days: [91], task: "Day 91: Final field cleanup and storage check." },
    { days: [92], task: "Day 92: Visit agri fair or expo if nearby." },
    { days: [93], task: "Day 93: Begin soaking seeds for next trial." },
    { days: [94], task: "Day 94: Revisit training notes or online agri courses." },
    { days: [95], task: "Day 95: Check government schemes for support." },
    { days: [96], task: "Day 96: Begin setting up nursery if needed." },
    { days: [97], task: "Day 97: Sharpen sickles, clean spray tanks." },
    { days: [98], task: "Day 98: Final sun-drying and cleaning of grains." },
    { days: [99], task: "Day 99: Label storage bags with crop year." },
    { days: [100], task: "Day 100: Final accounting and ledger update." },
    { days: [101], task: "Day 101: Prepare sowing calendar for next crop." },
    { days: [102], task: "Day 102: Dry tools, oil metal parts to avoid rust." },
    { days: [103], task: "Day 103: Check pest traps or storage repellents." },
    { days: [104], task: "Day 104: Review fertilizer use efficiency." },
    { days: [105], task: "Day 105: Stack grain bags on raised wooden pallets." },
    { days: [106], task: "Day 106: Remove weeds from bunds and channels." },
    { days: [107], task: "Day 107: Reorganize field layout if needed." },
    { days: [108], task: "Day 108: Discuss next crop ideas with neighbors." },
    { days: [109], task: "Day 109: Buy missing tools or implements." },
    { days: [110], task: "Day 110: Final rest day before next sowing season." }
  ],
},


sugarcane: {
  duration: 270,
  suggestions: [
    { days: [1], task: "Day 1: Select well-drained loamy soil with good sunlight." },
    { days: [2], task: "Day 2: Begin deep ploughing (30 cm) to loosen soil." },
    { days: [3], task: "Day 3: Apply 10–12 tons/acre of FYM or compost." },
    { days: [4], task: "Day 4: Level the field and make ridges and furrows." },
    { days: [5], task: "Day 5: Select healthy, disease-free cane setts (3-bud)." },
    { days: [6], task: "Day 6: Treat setts in fungicide/Trichoderma solution." },
    { days: [7], task: "Day 7: Place setts in furrows (30 cm spacing)." },
    { days: [8], task: "Day 8: Cover setts with soil and irrigate lightly." },
    { days: [9], task: "Day 9: Monitor for germination (7–10 days)." },
    { days: [10], task: "Day 10: Remove clods and ensure soil contact with setts." },
    { days: [11], task: "Day 11: Apply first irrigation if needed." },
    { days: [12], task: "Day 12: Check for termite damage in germinating setts." },
    { days: [13], task: "Day 13: Spray chlorpyrifos if termite observed." },
    { days: [14], task: "Day 14: Apply basal dose: 25% N, 100% P & K (50:50:50 kg/acre)." },
    { days: [15], task: "Day 15: Perform light hoeing to improve aeration." },
    { days: [16], task: "Day 16: Observe sprouting pattern and fill gaps." },
    { days: [17], task: "Day 17: Light irrigation and weed removal." },
    { days: [18], task: "Day 18: Spray pre-emergent herbicide if needed." },
    { days: [19], task: "Day 19: Ensure good drainage, especially in furrows." },
    { days: [20], task: "Day 20: Apply micronutrients if leaf discoloration is visible." },
    { days: [21], task: "Day 21: Begin tillering stage observation." },
    { days: [22], task: "Day 22: Remove weak tillers to encourage strong ones." },
    { days: [23], task: "Day 23: Check for early shoot borer infestation." },
    { days: [24], task: "Day 24: Spray chlorantraniliprole if shoot borer detected." },
    { days: [25], task: "Day 25: Light earthing up around base of plants." },
    { days: [26], task: "Day 26: Apply 2nd fertilizer dose (25% N)." },
    { days: [27], task: "Day 27: Irrigate field and check for soil moisture." },
    { days: [28], task: "Day 28: Begin intercultural operations to break crust." },
    { days: [30], task: "Day 30: Remove weeds manually or chemically." },
    { days: [35], task: "Day 35: Light hoeing and remove side tillers if excessive." },
    { days: [40], task: "Day 40: Apply 3rd dose: 25% N fertilizer + 20 kg Sulphur." },
    { days: [45], task: "Day 45: Earthing up and maintain furrow integrity." },
    { days: [50], task: "Day 50: Spray magnesium sulphate for better photosynthesis." },
    { days: [60], task: "Day 60: Ensure uniform irrigation in entire field." },
    { days: [65], task: "Day 65: Monitor for top shoot borer infestation." },
    { days: [70], task: "Day 70: Spray insecticide if damage noticed." },
    { days: [75], task: "Day 75: Apply 4th and final nitrogen dose (25%)." },
    { days: [80], task: "Day 80: Deep irrigation if dry spell occurs." },
    { days: [85], task: "Day 85: Monitor for iron deficiency (striped leaves)." },
    { days: [90], task: "Day 90: Spray ferrous sulphate if deficiency observed." },
    { days: [100], task: "Day 100: Light trimming of excessive leaves." },
    { days: [110], task: "Day 110: Begin grand growth stage observation." },
    { days: [120], task: "Day 120: Apply potash if internode elongation is slow." },
    { days: [130], task: "Day 130: Check for mealy bug or scale insect." },
    { days: [140], task: "Day 140: Spray neem oil or systemic insecticide if required." },
    { days: [150], task: "Day 150: Maintain good soil moisture." },
    { days: [160], task: "Day 160: Perform trash mulching to conserve moisture." },
    { days: [170], task: "Day 170: Continue irrigation during dry spells." },
    { days: [180], task: "Day 180: Monitor maturity stage – internode hardening begins." },
    { days: [190], task: "Day 190: Reduce irrigation frequency gradually." },
    { days: [200], task: "Day 200: Spray Potassium Nitrate to improve juice quality." },
    { days: [210], task: "Day 210: Remove dried leaves for aeration." },
    { days: [220], task: "Day 220: Start monitoring brix level (sugar content)." },
    { days: [230], task: "Day 230: Stop irrigation to improve cane hardness." },
    { days: [240], task: "Day 240: Field sanitation and bund maintenance." },
    { days: [250], task: "Day 250: Collect samples and test sugar level if possible." },
    { days: [260], task: "Day 260: Final cleanup, arrange labor for harvest." },
    { days: [265], task: "Day 265: Begin sugarcane harvesting when brix is 18–20%." },
    { days: [266], task: "Day 266: Cut canes at ground level, remove leaves and tops." },
    { days: [267], task: "Day 267: Transport canes quickly to nearby mill." },
    { days: [268], task: "Day 268: Dispose of trash by mulching or composting." },
    { days: [269], task: "Day 269: Start land prep for ratoon or next crop." },
    { days: [270], task: "Day 270: Record yield, cost and plan for next cycle." }
  ]
}

};

